/**
 * Substitute scoring data: flavor, texture, cooking context fit, availability, affordability (0–1).
 * Used by ranked substitutions to sort halal substitutes by practical usefulness.
 * Keys: original ingredient slug (or normalized name) -> array of { slug, displayName, flavor, texture, context, availability, affordability, reason, notes }
 */

export const DEFAULT_WEIGHTS = Object.freeze({
  flavor_similarity: 0.3,
  texture_similarity: 0.25,
  cooking_context_fit: 0.2,
  availability: 0.15,
  affordability: 0.1,
});

/**
 * Per-(original, substitute) scoring and copy.
 * Original key can be slug (bacon, gelatin, wine, mirin) or alias (white_wine -> use wine).
 */
export const SUBSTITUTE_SCORES = Object.freeze({
  bacon: [
    {
      slug: "smoked_turkey_bacon",
      displayName: "Smoked turkey bacon",
      flavor_similarity: 0.9,
      texture_similarity: 0.85,
      cooking_context_fit: 0.95,
      availability: 0.85,
      affordability: 0.7,
      reason: "Closest match in flavor and crisp texture; works in most recipes.",
      notes: "Add a little oil if the turkey bacon is lean. 1:1 swap.",
    },
    {
      slug: "beef_bacon_halal",
      displayName: "Halal beef bacon",
      flavor_similarity: 0.85,
      texture_similarity: 0.8,
      cooking_context_fit: 0.9,
      availability: 0.6,
      affordability: 0.5,
      reason: "Smoky, cured profile similar to bacon; halal-certified.",
      notes: "Check for halal certification. Good for breakfast and wrapping.",
    },
    {
      slug: "turkey_ham_halal",
      displayName: "Halal turkey ham",
      flavor_similarity: 0.6,
      texture_similarity: 0.65,
      cooking_context_fit: 0.65,
      availability: 0.7,
      affordability: 0.75,
      reason: "Cured, savory option when bacon is used for flavor.",
      notes: "Better for dicing than streaky strips. Less crisp.",
    },
    {
      slug: "halal_beef_pastrami",
      displayName: "Halal beef pastrami",
      flavor_similarity: 0.55,
      texture_similarity: 0.5,
      cooking_context_fit: 0.5,
      availability: 0.65,
      affordability: 0.6,
      reason: "Bold, salty flavor; works in sandwiches and cooked dishes.",
      notes: "Not a direct texture match; use where flavor is the main role.",
    },
  ],
  wine: [
    {
      slug: "white_grape_juice_plus_vinegar",
      displayName: "White grape juice + vinegar",
      flavor_similarity: 0.8,
      texture_similarity: 0.9,
      cooking_context_fit: 0.9,
      availability: 0.95,
      affordability: 0.95,
      reason: "Acidity and fruitiness mimic white wine in deglazing and sauces.",
      notes: "About 3 parts juice to 1 part white wine vinegar or rice vinegar.",
    },
    {
      slug: "grape_juice_plus_vinegar",
      displayName: "Grape juice + vinegar",
      flavor_similarity: 0.75,
      texture_similarity: 0.9,
      cooking_context_fit: 0.85,
      availability: 0.95,
      affordability: 0.95,
      reason: "Works for both red and white wine in cooking.",
      notes: "Use 3 parts juice + 1 part vinegar. Non-alcoholic wine is an option if available.",
    },
    {
      slug: "non_alcoholic_wine",
      displayName: "Non-alcoholic wine",
      flavor_similarity: 0.85,
      texture_similarity: 0.95,
      cooking_context_fit: 0.85,
      availability: 0.5,
      affordability: 0.5,
      reason: "Closest flavor match; check that alcohol is fully removed.",
      notes: "Verify 0% alcohol. Availability varies by region.",
    },
    {
      slug: "rice_vinegar",
      displayName: "Rice vinegar",
      flavor_similarity: 0.55,
      texture_similarity: 0.9,
      cooking_context_fit: 0.7,
      availability: 0.8,
      affordability: 0.85,
      reason: "Mild acidity for deglazing; good in Asian-style dishes.",
      notes: "Less fruity than wine. Combine with a little juice if needed.",
    },
    {
      slug: "chicken_or_vegetable_broth",
      displayName: "Chicken or vegetable broth",
      flavor_similarity: 0.4,
      texture_similarity: 0.95,
      cooking_context_fit: 0.75,
      availability: 0.95,
      affordability: 0.9,
      reason: "Adds moisture and savor; no alcohol.",
      notes: "Best when wine is used for liquid rather than acidity.",
    },
  ],
  white_wine: [
    // Same as wine; key normalized in service
    {
      slug: "white_grape_juice_plus_vinegar",
      displayName: "White grape juice + vinegar",
      flavor_similarity: 0.85,
      texture_similarity: 0.9,
      cooking_context_fit: 0.95,
      availability: 0.95,
      affordability: 0.95,
      reason: "Best direct swap for white wine in sauces and deglazing.",
      notes: "3 parts white grape juice to 1 part white wine vinegar or rice vinegar.",
    },
    {
      slug: "grape_juice_plus_vinegar",
      displayName: "Grape juice + vinegar",
      flavor_similarity: 0.75,
      texture_similarity: 0.9,
      cooking_context_fit: 0.9,
      availability: 0.95,
      affordability: 0.95,
      reason: "Widely available; works in most white-wine applications.",
      notes: "3 parts juice + 1 part vinegar.",
    },
    {
      slug: "non_alcoholic_wine",
      displayName: "Non-alcoholic white wine",
      flavor_similarity: 0.9,
      texture_similarity: 0.95,
      cooking_context_fit: 0.9,
      availability: 0.5,
      affordability: 0.5,
      reason: "Closest match when available.",
      notes: "Verify 0% alcohol.",
    },
    {
      slug: "rice_vinegar",
      displayName: "Rice vinegar",
      flavor_similarity: 0.5,
      texture_similarity: 0.9,
      cooking_context_fit: 0.7,
      availability: 0.8,
      affordability: 0.85,
      reason: "Mild acidity; good for pan sauces.",
      notes: "Add a touch of sugar or juice for sweetness if needed.",
    },
  ],
  gelatin: [
    {
      slug: "agar_agar",
      displayName: "Agar agar",
      flavor_similarity: 0.95,
      texture_similarity: 0.85,
      cooking_context_fit: 0.85,
      availability: 0.75,
      affordability: 0.8,
      reason: "Plant-based; sets firmer than gelatin. No animal source.",
      notes: "Use about half the amount of gelatin by weight. Reheat to activate.",
    },
    {
      slug: "halal_beef_gelatin",
      displayName: "Halal beef gelatin",
      flavor_similarity: 0.98,
      texture_similarity: 0.98,
      cooking_context_fit: 0.98,
      availability: 0.6,
      affordability: 0.6,
      reason: "Same texture and behavior as gelatin; must be halal-certified.",
      notes: "1:1 replacement. Check certification on the packet.",
    },
    {
      slug: "pectin",
      displayName: "Pectin",
      flavor_similarity: 0.9,
      texture_similarity: 0.6,
      cooking_context_fit: 0.65,
      availability: 0.9,
      affordability: 0.85,
      reason: "Plant-based; best for jams and fruit gels.",
      notes: "Not ideal for clear gels or mousses. Use agar for those.",
    },
    {
      slug: "cornstarch_slurry",
      displayName: "Cornstarch slurry",
      flavor_similarity: 0.7,
      texture_similarity: 0.5,
      cooking_context_fit: 0.5,
      availability: 0.95,
      affordability: 0.95,
      reason: "Thickens sauces and fillings; not a gel set.",
      notes: "Use where a light thickener is needed, not for molded gels.",
    },
  ],
  mirin: [
    {
      slug: "sugar_plus_rice_vinegar",
      displayName: "Sugar + rice vinegar",
      flavor_similarity: 0.85,
      texture_similarity: 0.9,
      cooking_context_fit: 0.9,
      availability: 0.95,
      affordability: 0.95,
      reason: "Sweet-tangy balance close to mirin; no alcohol.",
      notes: "About 1 tsp sugar + 1 tsp rice vinegar per tbsp mirin. Adjust to taste.",
    },
    {
      slug: "halal_mirin",
      displayName: "Halal mirin (alcohol-free)",
      flavor_similarity: 0.95,
      texture_similarity: 0.95,
      cooking_context_fit: 0.95,
      availability: 0.5,
      affordability: 0.6,
      reason: "Direct replacement when you can find alcohol-free mirin.",
      notes: "Check label for 0% alcohol. Available at some Asian and halal grocers.",
    },
    {
      slug: "rice_vinegar_plus_sugar",
      displayName: "Rice vinegar + sugar or honey",
      flavor_similarity: 0.8,
      texture_similarity: 0.9,
      cooking_context_fit: 0.85,
      availability: 0.9,
      affordability: 0.9,
      reason: "Simple, widely available swap for glazes and teriyaki.",
      notes: "Mild vinegar with a pinch of sugar or honey. Add a splash of water if needed.",
    },
    {
      slug: "apple_juice_plus_vinegar",
      displayName: "Apple juice + rice vinegar",
      flavor_similarity: 0.65,
      texture_similarity: 0.85,
      cooking_context_fit: 0.7,
      availability: 0.9,
      affordability: 0.9,
      reason: "Fruity-sweet with acidity; works in some glazes.",
      notes: "Use less juice than vinegar to avoid excess sweetness.",
    },
  ],
});

/** Map ingredient phrase (normalized) to key in SUBSTITUTE_SCORES. */
export const INGREDIENT_SCORE_KEY_ALIASES = Object.freeze({
  white_wine: "white_wine",
  "white wine": "white_wine",
  red_wine: "wine",
  "red wine": "wine",
  cooking_wine: "wine",
  wine: "wine",
});
